---
volumes:
  git-sync_data: {}

services:

  git-sync:
    container_name: git-sync
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./containers/Dockerfile
      args:
        DEBIAN_IMG_VERSION: ${CONTAINER_IMG_VER:-bookworm-slim}
    working_dir: /git-sync
    # user: "1000:1000"
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - ./mirrors:/git-sync/mirrors
      - ${GIT_SYNC_DATA_DIR:-git-sync_data}:/git-sync/repositories
      ## Mount host SSH directory in the container by default.
      #  Provide a different path to an SSH directory with a config file
      #  & SSH key(s) for the container to use.
      - ${SSH_DIR:-./containers/ssh}:/root/.ssh
    command: bash -c "cron && tail -f /var/log/cron.log"
    ## Uncomment for debugging, comment the command above
    # command: sleep infinity
