#!/bin/bash

## Set variable to path where script was launched from
CWD=$(pwd)

# Change to the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $SCRIPT_DIR || exit 1

if ! command -v ssh-keygen &> /dev/null; then
    echo "[ERROR] SSH does not seem to be installed, ssh-keygen command failed. Exiting."
    cd $CWD

    exit 1
else
    echo "SSH installed, continuing."
fi

if [[ ! -d "${SCRIPT_DIR}/ssh" ]]; then
    echo "Creating SSH directory: ${SCRIPT_DIR}/ssh"

    mkdir -pv "${SCRIPT_DIR}/ssh"
else
    echo "SSH directory already exists: {SCRIPT_DIR}/ssh}. Continuing"
fi

if [[ ! -f "${SCRIPT_DIR}/ssh/config" ]]; then
    echo "Creating SSH config file: ${SCRIPT_DIR}/ssh/config"

    cat <<EOF > "${SCRIPT_DIR}/ssh/config"
#######################################################
# SSH config for Docker container                     #
#                                                     #
# This configuration will not be used on the host OS. #
# This file was generated by the generate-ssh-keys.sh #
# script. Feel free to make changes to it, but keep it#
# in the .gitignore.                                  #
#######################################################

Host github.com
  User git
  IdentityFile ~/.ssh/git_mirror_id_rsa
  StrictHostKeyChecking no

Host codeberg.org
  User git
  IdentityFile ~/.ssh/git_mirror_id_rsa
  StrictHostKeyChecking no

Host gitlab.com
  User git
  IdentityFile ~/.ssh/git_mirror_id_rsa
  StrictHostKeyChecking no
EOF
else
    echo "SSH config file already exists: ${SCRIPT_DIR}/ssh/config. Continuing"
fi

if [[ ! -f "${SCRIPT_DIR}/ssh/git_mirror_id_rsa" ]]; then
    echo "Generating SSH key pair for git mirrors"
    ssh-keygen -t rsa -b 4096 -f "${SCRIPT_DIR}/ssh/git_mirror_id_rsa" -N ""
else
    echo "SSH key pair already exists: ${SCRIPT_DIR}/ssh/git_mirror_id_rsa}. Continuing"
fi

if [[ -d "${SCRIPT_DIR}/ssh" ]]; then
    echo "Setting permissions on SSH directory: ${SCRIPT_DIR}/ssh"

    chmod 700 "${SCRIPT_DIR}/ssh"
    if [[ $? -ne 0 ]]; then
        echo "[ERROR] Setting permissions on ${SCRIPT_DIR}/ssh failed. Exiting."
        cd $CWD
        exit 1
    else
        echo "Set chmod 700 on ${SCRIPT_DIR}/ssh"
    fi

    if [[ -f "${SCRIPT_DIR}/ssh/git_mirror_id_rsa" ]]; then
        chmod 600 "${SCRIPT_DIR}/ssh/git_mirror_id_rsa"
        if [[ $? -ne 0 ]]; then
            echo "[ERROR] Setting permissions on ${SCRIPT_DIR}/ssh/git_mirror_id_rsa failed. Exiting."
            cd $CWD
            exit 1
        else
            echo "Set chmod 600 on ${SCRIPT_DIR}/ssh/git_mirror_id_rsa"
        fi
    fi
else
    echo "[ERROR] SSH directory does not exist, but should. Do you have permissions to write to path ${SCRIPT_DIR}/ssh?"
    echo "Exiting"
    cd $CWD
    exit 1
fi    

if [[ $? -ne 0 ]]; then
    echo "[ERROR] SSH key generation failed. Exiting."
    cd $CWD
    exit 1
else
    echo "[SUCCESS] SSH directory configured. Exiting."
    cd $CWD
    exit 0
fi
